version: '3.7'
services:
  postgres:
    image: postgres:11-alpine
    container_name: rare-basket-postgres
    # copying the setup.sql file in the /docker-entrypoint-initdb.d/ directory
    # the script run on start by the postgres container
    # and creates the appropriate databases and users
    volumes:
      - ./backend/database/setup:/docker-entrypoint-initdb.d/:cached
    ports:
      - 5432:5432

  smtp:
    image: mailhog/mailhog
    container_name: rare-basket-smtp
    ports:
      - 25:1025
      - 8025:8025

  keycloak:
    image: quay.io/keycloak/keycloak:9.0.2
    container_name: rare-basket-keycloak
    volumes:
      - ./keycloak:/tmp/keycloak
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
      KEYCLOAK_IMPORT: /tmp/keycloak/rare-basket-realm.json
      DB_VENDOR: h2
    ports:
      - 8082:8080
