version: '3.7'
services:
  postgres:
    # 11-alpine
    image: postgres@sha256:362a63cb1e864195ea2bc29b5066bdb222bc9a4461bfaff2418f63a06e56bce0
    container_name: rare-basket-postgres
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
      - ENV=dev
    # copying the setup.sql file in the /docker-entrypoint-initdb.d/ directory
    # the script run on start by the postgres container
    # and creates the appropriate databases and users
    volumes:
      - ./backend/database/setup/setup.sql:/docker-entrypoint-initdb.d/setup.sql:cached
    ports:
      - 5432:5432

  smtp:
    # latest
    image: mailhog/mailhog@sha256:8d76a3d4ffa32a3661311944007a415332c4bb855657f4f6c57996405c009bea
    container_name: rare-basket-smtp
    ports:
      - 25:1025
      - 8025:8025

  keycloak:
    # 9.0.2
    image: quay.io/keycloak/keycloak@sha256:292d9cf5f767d9d8c7737c119e1541538dcc26fe6c2fb98f073a7aa21a40d42c
    container_name: rare-basket-keycloak
    volumes:
      - ./keycloak:/tmp/keycloak
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
      KEYCLOAK_IMPORT: /tmp/keycloak/rare-basket-realm.json
      DB_VENDOR: h2
    ports:
      - 8082:8080
