version: 2.1 # use CircleCI 2.1
orbs:
  browser-tools: circleci/browser-tools@2.1.1
jobs: # a collection of steps
  build: # runs not using Workflows must have a `build` job as entry point
    machine:
      image: ubuntu-2004:current
    working_directory: ~/rare-basket # directory where steps will run
    steps: # a collection of executable commands
      - browser-tools/install_chrome
      # check out source code to working directory
      - checkout
      # start postgresql and keycloak
      - run: docker compose up -d
      - run: docker ps
      - run: ./gradlew check build
