rare-basket:
  database:
    host-and-port: localhost:5432
  mail:
    from: noreply@rare-basket.fr
    base-url: http://localhost:4201
  document-storage:
    path: /tmp/rare-basket-storage

server:
  compression:
    enabled: true
    mime-types:
      - application/json
      - application/javascript
      - text/html
      - text/css
      - text/plain
  port: 8081
  servlet:
    context-path: /rare-basket

spring:
  datasource:
    url: jdbc:postgresql:rarebasket
    username: rarebasket
    password: rarebasket
  servlet:
    multipart:
      # if you change this, it also needs to be changed in the frontend code, which checks the file size before uploading
      max-file-size: 10MB
      max-request-size: 20MB
  mail:
    host: localhost
    username:
    password:
    port: 25

# These settings are documented here: https://www.keycloak.org/docs/latest/securing_apps/index.html#_java_adapter_config
keycloak:
  realm: rare-basket
  resource: rare-basket
  auth-server-url: http://localhost:8082/auth
  ssl-required: external
  public-client: true # necessary for basic auth. Not sure why.
  principal-attribute: preferred_username
  bearer-only: true
  enable-basic-auth: true

---
spring:
  profiles: test
  datasource:
    url: jdbc:postgresql://${rare-basket.database.host-and-port}/rarebasket_test
    hikari:
      maximum-pool-size: 2
  jpa:
    hibernate:
      ddl-auto: validate
