rare-basket:
  database:
    host-and-port: localhost:5432
  mail:
    from: noreply@rare-basket.fr
    base-url: http://localhost:4200

server:
  compression:
    enabled: true
    mime-types:
      - application/json
      - application/javascript
      - text/html
      - text/css
      - text/plain
spring:
  datasource:
    url: jdbc:postgresql:rarebasket
    username: rarebasket
    password: rarebasket
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 20MB
  mail:
    host: localhost
    username:
    password:
    port: 25

---
spring:
  profiles: test
  datasource:
    url: jdbc:postgresql://${rare-basket.database.host-and-port}/rarebasket_test
    hikari:
      maximum-pool-size: 2
  jpa:
    hibernate:
      ddl-auto: validate
